<#################################################################################################
 2020-07-01 (c)Vladimir Capek

 Očekávané vstupy: 
 $excelFileName = "CEZ-AIP-Label-Template-v4_revIKB-AIPLimits.xlsx" Jméno XLS Souboru

 Skript z Excelu udelá CSV soubory, pokud u skriptu není již CSV.
 K převodu musí být na stanici MS Excel
 Pro kokertní konvert ceskych textu je treba zajistit xls soubor v Unicode
 poté tento skript zpracovává xls soubor a jeho list  jmenem: Label ze ktereho vniklo CSV

#################################################################################################> 

<#################################################################################################
# Prihlášení do PS EOA
$UserCredential = Get-Credential -UserName user@company.onmicrosoft.com -Message "Connect to Azure AIP"

$UserCredential = Get-Credential -UserName acseclabadmin@acinfraseclab.onmicrosoft.com -Message "Connect to Azure AIP"
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.compliance.protection.outlook.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
Import-PSSession $Session  ###TOHLE JE KLICOVE POR COMMANDY

#  PROHLASENI DO AIP SERVICE <pro načtení RMS šifrovacích labelů stale potřeba>
$AdminCredentials = Get-Credential "user@domain.onmicrosoft.com"
Connect-AipService -Credential $AdminCredentials 

Get-PSSession

#################################################################################################> 


CLS
Clear-Host
Remove-Variable * -ErrorAction SilentlyContinue
$Error.clear()

$AdminCredentials = Get-Credential "user@domain.onmicrosoft.com"
$azurelogonname =  "user@domain.onmicrosoft.com"

# CESTA KDE JE SPUSTEN SKRIP
$scriptpath = Split-Path -parent $MyInvocation.MyCommand.Definition

# $scriptpath =  $PSScriptRoot

<##################################################################################
#                DEFINOVANI PROMMENNYCH PRO BEH PROGRAMU
##################################################################################> 
 

[bool]$runwithpause    =  0          # True/False - True = program nebude cekat na mačkání mezerníku po krocích 
[bool]$runwithdebugg   =  1          # True/False - True = program bude vypisovat vice detailu 
# Pozor - Skript nemuzese začínat na SubLabelech... 
$Startujnaradku        =  1        # 1 je výchozí hodnota rádku na kterém se začíná, vyssi čísla se používají pro ladení prograamu
$Skoncinaradku         =  10         # 0 = neskonci
[Bool]$WriteTemplate   =  0          # 1 - ZAPISOVACI REZIM !!!
[Bool]$ReWriteTemplate  = 0
$REWriteTemplatestart   =  0          # def 0  - hodnoty od 02-44 - PREPISOVACI REZIM od politiky číslo
$REWriteTemplatekonec   =  45         # def 44 - hodnoty od 02-44 - PREPISOVACI REZIM do politiky číslo
[bool]$orgstruktury     = 0           # Po doknceni labelu v XLS se pokracuje smyckou v OrgStr listu.

<#  ZOBRAZENI HODNOT SE KTERYMI SE PRACUJE V PROGRAMU NACTENYCH Z CLS SOUBORU
##################################################################################
00: Label_ID(generated by SkČ).................................. - L00008
01: Priority.................................................... - 2010
02: Enabled..................................................... - ON
03: Prefix-EN................................................... - Internal
04: Prefix-CZ................................................... - Interní
05: OU.......................................................... - TEST
06: Suffix-EN................................................... - 
07: Suffix-CZ................................................... - 
08: Label display name EN....................................... - Internal-TEST
09: Label display name CZ....................................... - Interní-TEST
10: Description EN.............................................. - 
11: Description CZ.............................................. - Informace nejsou veřejně přístupné a tvoří know-how organizace. Ochrana aktiv nen
12: Color (of a label).......................................... - Green
13: Add notes for administrator use(Enter notes for internal hou - x
14: Documents with this label have a header..................... - ON
15: Header text................................................. - Interní / Internal
16: Header font size............................................ - 10
17: Header font name............................................ - Default
18: Header color................................................ - Black
19: Header alignment............................................ - Right
20: Documents with this label have a footer..................... - OFF
21: Footer text................................................. - x
22: Footer font size............................................ - x
23: Footer font name............................................ - x
24: Footer color................................................ - x
25: Footer alignment............................................ - x
26: Documents with this label have a watermark.................. - OFF
27: Watermark text.............................................. - x
28: Watermark font size......................................... - x
29: Watermark font name......................................... - x
30: Watermark color............................................. - x
31: Watermark layout............................................ - x
32: Configure conditions for automatically applying this label(a - x
33: Set permissions for documents and emails containing this lab - Remove Protection
34: RMS Template Name........................................... - x
35: Protection settings......................................... - x
36: Select the protection action type........................... - x
37: Set user-defined permissions:In Outlook apply Do Not Forward - x
38: Set user-defined permissions:In Word, Excel, PowerPoint and  - x
39: Content expiration.......................................... - x
40: Allow offline access........................................ - x
41: Add permissions............................................. - x
42: Users....................................................... - x
43: Permission Type............................................. - x
44: Permissions................................................. - x
#>


[Bool]$zpracujiOU      =  0          # Bude pokracovat i s definovanými OU
$ZacninaOUcislo        =  0
$JednaPolitikaRadku    =  6          # Bez detecke skriptu - kolik ma CSV soubor jíz nadefinovanch labelu pro jednu politiku
$vzdalenost            =  60
[bool]$tartTransskriptLabelu =   1
[bool]$tartTransskriptProgramu = 1


$stav=0
$opacko = 0
$ou=0

$excelFileName = "CEZ-AIP-Label-Production-Final_u3.xlsx"


# Get-Process -Name WmiPrvSE | Select-Object -Property BasePriority,Id,SessionId,WorkingSet |

if ($tartTransskriptLabelu -eq $false) 
{
if ($tartTransskriptProgramu -eq $true) {Start-Transcript -path "$scriptpath\AIPLabelLogfile_$((Get-Date).ToString('MM-dd-yyyy_hh-mm')).log" }
}


<#################################################################################################
#   
#  Generuji z XLS CSV soubory
# 
#  Pozor na convert z XLS na CSV tak aby nedoslo ke spatnemu konvertu CZ znaku
# 
#################################################################################################>


Function ExportWSToCSV ($excelFileName, $csvLoc){

Write-Host "XLS Soubor nesmí v textech obsahovat znak středíku !!!! "

    $excelFile = ($csvLoc +"\"+ $excelFileName)
    Write-host "Converting XML file: $csvLoc\$excelFileNam" -f Yellow

    $E = New-Object -ComObject Excel.Application 
    $E.Visible = $false
    $E.DisplayAlerts = $false
    $wb = $E.Workbooks.Open($excelFile)
    foreach ($ws in $wb.Worksheets)
    {
        $n = $excelFileName + "_" + $ws.Name
    Write-host "Converting XML list to CSV: $n .csv" -f Yellow

    if ($n -like "*$filter*" ) {
            Write-host "Converting... XML list to CSV: $n .csv" -f Yellow
            $ws.SaveAs($csvLoc +"\"+ $n + ".csv", 6)

 }
       
    }
    $E.Quit()
}


# ExportWSToCSV -excelFileName $excelFileName -csvLoc $scriptpath 


$filename = "*label_*.csv"
# TEXT Existence soboru
if ( (Test-Path ($scriptpath + "\" + $filename) -PathType Any) -eq $false)
{
# Pokud není soubor CSV tak se vygneruje (tohle šetří čas při opakovaném spouštění skriptu)
write-host "Vytvářím z XLS jednotlivé listy jako CSV soubory CSV...."
$filter = "label_"
ExportWSToCSV -excelFileName $excelFileName -csvLoc $scriptpath
$file1 = Get-ChildItem *label_*.csv -Path $scriptpath -Name
#  }
}
else
{
# Načítání hodnot z CSV souborů - Labely
$file1 = Get-ChildItem *label_*.csv -Path $scriptpath -Name
$nactenecsv = Import-Csv -Path $scriptpath\$file1  -Encoding Default -Delimiter ','
$linesoncsv = $nactenecsv.Count -1
}


$filename = "*OrgStr*.csv"
# TEXT Existence soboru
if ( (Test-Path ($scriptpath + "\" + $filename) -PathType Any) -eq $false)
{
# Pokud není soubor CSV tak se vygneruje (tohle šetří čas při opakovaném spouštění skriptu)
write-host "Vytvářím z XLS jednotlivé listy jako CSV soubory CSV...."
$filter = "OrgStr"
ExportWSToCSV -excelFileName $excelFileName -csvLoc $scriptpath
$file2 = Get-ChildItem *OrgStr*.csv -Path $scriptpath -Name
#  }
}
else
{
# Načítání hodnot z CSV souborů - Seznam Organizaci
$file2 = Get-ChildItem *OrgStr*.csv -Path $scriptpath -Name
$nactenecsv2 = Import-Csv -Path $scriptpath\$file2  -Encoding Default -Delimiter ','
$linesoncsv2 = $nactenecsv2.Count -1
}



<#################################################################################################
#   
#  PROGRAMOVE FUNKCE
#   
#################################################################################################> 

function FNBarva($BarvaIn) {
$barva = "#000000" # Default Color for new Teplates
# if ($BarvaIn -ne "x") {$Script:barva  = "#"+[Convert]::ToString([System.Drawing.ColorTranslator]::ToWin32([System.Drawing.Color]::($BarvaIn)), 16).PadLeft(6, '0') }
if ($BarvaIn -ne "x") {$Script:barva = "#" + [System.Drawing.Color]::($BarvaIn).R.ToString("x2") + [System.Drawing.Color]::($BarvaIn).G.ToString("x2") + [System.Drawing.Color]::($BarvaIn).B.ToString("x2") }
}

function FNJmenoRadku($JmenoRadku) {
IF ($JmenoRadku.Length -eq "")       {     write-host -nonewline; $Script:spaces = '.' * ($vzdalenost )}
# Vykresluje jeden znak
IF ($JmenoRadku.Length -eq 1)           {$spaces = "$JmenoRadku" * ($vzdalenost) 
                                           Write-host $predtext$spaces -ForegroundColor Yellow -NoNewline }
IF ($JmenoRadku.Length -gt 1)           {  Write-host $predtext -ForegroundColor Yellow -NoNewline 

IF ($JmenoRadku.Length -gt $vzdalenost ) {Write-host $JmenoRadku.Substring(0,$vzdalenost)"- " -ForegroundColor Yellow -NoNewline }
else
{                                          Write-host $JmenoRadku -ForegroundColor Yellow -NoNewline
                                $pocet = (($vzdalenost) - $JmenoRadku.Length)
                                $spaces = '.' * ($pocet) +" - "
                                           write-host $spaces -f gray -NoNewline }}
}
    
function FNWrite-Host($JmenoRadku) {

         switch ($JmenoRadku){
         OFF     {$BarvaRadku ="Gray" }
         x       {$BarvaRadku ="Gray" }
         ON      {$BarvaRadku ="Green"}
         True    {$BarvaRadku ="Green" }
         ERROR   {$BarvaRadku ="Red"}
         False   {$BarvaRadku ="Gray"}
         default {$BarvaRadku ="White"} 
         }
     
# Když je Debuggmode on tak se řádek s hodnotou nezkracuje. 
        if ($JmenoRadku.Length -gt $vzdalenost -and $runwithdebugg -eq 0) { write-host (""+$JmenoRadku.Substring(0,$vzdalenost)) -F $BarvaRadku }
        else                                    { write-host (""+$JmenoRadku) -F $BarvaRadku }
}

Function FNListHodnot($text) {
$predtext = $text.tostring("00")+": "

$Output3 = @();
$Output4 = @();

for ($i = 0; $i -lt $pocethodnot; $i++)
{ 
if ($test -eq "0") {}
GetCSVLineVariable($i)$Output3 += $sloupec
$Output4 += $hodnota

}

# Prevod promenné z Funkce do promenne kterou mohu použít ve sktiptu
$script:output = $output4
$script:output1 = $output3

}

Function FNVypishodnot {
for ($i = 0; $i -lt $pocethodnot; $i++) {
$predtext = $i.tostring("00")+": "


if ($REWriteTemplatestart -le $i -and $REWriteTemplatekonec -ge $i  )
{ 
FNJmenoRadku ($Output1[$i]) ; FNwrite-host ($output[$i])
}

}
}


function FNInfoHeader{
write-host "Počet řádků: "
write-host "$file1 : `t $linesoncsv "
write-host "$file2 : `t $linesoncsv2 "


$predtext = "=========="
FNJmenoRadku ("="); write-host " - " -nonewline ; FNJmenoRadku ("=");write-host ""
write-host "Kontorla! - Jmána sloupců a hodnot z prvního řádku CSV" -f Green -b Black

$predtext = "CSV: "

GetCSVLine (1)
FNListHodnot
}


Function GetCSVLine ($cisloradku) {
if ($cisloradku -le $linesoncsv) {
    # rozebere CSV na radky
    $radek =  $nactenecsv[$cisloradku]

    # zajistit odebrani substringem
    $radek = $radek -replace "@{",""
    $radek = $radek -replace "}",""
    $script:DatavCSV2 = $radek -split('; ')
    $script:pocethodnot = $DatavCSV2.Count

}
}

Function GetCSVLineVariable($cislohodnoty) {
    if ($cislohodnoty -le $pocethodnot) {
    # rozebere CSV radek na jmeno sloupce a hodnotu
    $script:Sloupec,$script:hodnota = $DatavCSV2[$cislohodnoty] -split("="),0
    $script:Sloupec = $script:Sloupec -replace "`n",""
    }
}




Function FNListExistingAzureLabels() {
if ($jepssession[0].id -gt 0 ){

if ($AIPExistujiciLabely -like "" -and $runwithdebugg -eq 1 ) {  $AIPExistujiciLabely = get-label | select Guid, Name, displayname,  priority, Comment, Disabled, CreatedBy, LastMidifiedBy }
if ($AIPExistujiciLabely -like "" -and $runwithdebugg -eq 0 ) {  $AIPExistujiciLabely = get-label | select Name, displayname, priority, Disabled }

}

get-label | select Guid, Name, displayname,  priority, Comment, Disabled, CreatedBy, LastMidifiedBy |  Where-Object {$_.guid="162429d9-fb7a-4915-8c7b-17695df90d83"}


 
write-host " Seznam existujících šablon v AIP"  -ForegroundColor Yellow
$AIPExistujiciLabely | FT 
if ($runwithpause -eq $true) { start-sleep 2 }
}




<#################################################################################################
#   
#  PROGRAM BEGIN 
#   
#################################################################################################> 
$starttime = (get-date).Hour*24 + (get-date).Minute*60 + (get-date).Second

FNWrite-Host ("Skript Run Time: `t $datum " )
FNWrite-Host ("Skript Run Path: `t $scriptpath ")


#
#
#  DETEKUJI OPACKO (kolik je v jedné politice labelu) 
#
#  (Tohle by se dalo případně doprogramovat na autodetekce) !!! 
 
$opackocelkem = 6


# Get-AipServiceTemplate - Vyzdaduje Login do Azure

if ($AIPExistujiciRMSTemplates -eq $null) {



Connect-AipService -Credential $AdminCredentials



}
$AIPExistujiciRMSTemplates = Get-AipServiceTemplate





<#################################################################################################
#   
#  Debugg Zobrazení ukázkového načtění dat z CSV - první datová řádek
#   
#################################################################################################> 

# if ($runwithdebugg -eq $true) { $predtext = "FNHeader "; FNInfoHeader }


<#################################################################################################
# Načítám seznam existujících šablon v Azure
#################################################################################################> 


$jsemzalogovan = Get-PSSession | select name | FT

# Kontrola prihlašení do Azure
if ($jsemzalogovan -eq $null ) {

if ($runwithdebugg -eq $true) {
write-host "`n`n Načítám seznam existujících šablon v AIP před spuštěním skriptu`n"  -ForegroundColor Cyan
}


# $UserCredential = Get-Credential -UserName acseclabadmin@acinfraseclab.onmicrosoft.com -Message "Connect to Azure AIP"

$UserCredential = Get-Credential -UserName $azurelogonname -Message "Connect to Azure AIP"


$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.compliance.protection.outlook.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
Import-PSSession $Session  ###TOHLE JE KLICOVE POR COMMANDY
}


$jepssession = Get-PSSession | select id
$jepssession[0].id

FNListExistingAzureLabels
write-host " Byly načteny šablony z Azure"


Function FNEndRadekPause($text){
###############################################################################################################
### END RADEK zmackni SPACE
###############################################################################################################
if ($runwithpause -eq $true) {
  # write-host "Press Space to next Label..... " -ForegroundColor Black -BackgroundColor White
  write-host "`n" 
  $text =  'Zmáčkněte "Space" pro '+$text+' ..... '
  Read-Host -prompt $text
}
}

Function FNHeaderProgramu() {
<#################################################################################################
# HEADER PROGRAMU
#################################################################################################>  

if ($runwithdebugg -eq $false) {
# CLS
}


if ($runwithdebugg -eq $true) { write-host "DEBUGG: FNHeaderProgramu" }
  
    write-host "Průběh Programu - zpracovávaní řádků: " -f Green
    write-host " [" $r.ToString("000") "/" $linesoncsv.ToString("000") "] Labelu v základním XLS" -ForegroundColor Green 
 #   write-host " [" $ou.ToString("000") "/" $linesoncsv2.ToString("000") "] OU kterým se budou generovat Labely " -ForegroundColor Green
 #   write-host " [" $opacko.ToString("000") "/" $opackocelkem.ToString("000") "] poradí Labelu pro OU" -ForegroundColor Green
 
 $stav = ($r+($ou*6)+$opacko)

 if ($skoncinaradku -ne 0) 
 {
 $celkem = 1+($skoncinaradku - $Startujnaradku)
 $stav   = $provadimakci
 }

 $proc = ($stav/$celkem)*100
 if ($proc -gt 100) {$proc=100}
 $proc2 = $proc.ToString("00.0")
 $chyb = $Error.Count

# $casted = (get-date).Hour*24 + (get-date).Minute*60 + (get-date).Second
# $odhadovanycas = (($casted - $starttime)/$proc)*(100-$proc)
#  write-host " %  Odhadovaný čas: "$odhadovanycas.ToString("000") -Nonewline 

# Write-Progress -Activity "Progress" -Status "$stav / $celkem Complete:" -PercentComplete $proc;
Write-Progress -Activity "Creating MIP Labels   Chyb: $chyb " -Status "$stav / $celkem Complete:   $proc2 %" -PercentComplete $proc;



write-host "Počet hodnot z aktuálně načteného csv řádku:  "  -f Green -Nonewline
write-host "[$pocethodnot] "     -ForegroundColor Green
write-host $file2  -f Yellow
 


$predtext = ""
FNJmenoRadku ("="); write-host " - " -nonewline 
$predtext = "Jmena a sloupce: "
    if ( $runwithdebugg -eq 1) {FNWrite-Host ("= - === Pri Debugg se nezkracují hodnoty! ===========") }
    else                       {FNWrite-Host ("============================================================================")}
    
          
    }
        





Function FNTvorbaLabelu {


if ($runwithdebugg -eq $true) { write-host "DEBUGG: FNTvorbaLabelu" 
FNJmenoRadku("Overi se Existence LABELU: " + $output[0]); write-host "pro OU:" $labely -ForegroundColor gray
}


# Ověřím, zdali šablona už existuje

$AIPExistujiciLabely = get-label | select Name, displayname, priority, Disabled


$vysledek =  $AIPExistujiciLabely  | where {$_.Name -eq $output[0]}
$vysledek2 = $AIPExistujiciLabely  | where {$_.displayname -eq $output[8]}



# Ochrana proti překročení povolených znaků (Exhange limit 1000, AIP UL limit 160)
if ($output[10].Length -gt 999) { $output[10] = $output[10].Substring(0,999) }
if ($output[11].Length -gt 999) { $output[11] = $output[11].Substring(0,999) }
if ($output[13].Length -gt 999) { $output[13] = $output[13].Substring(0,999) }


if ($vysledek.count -eq 0 -and $vysledek2.count -eq 0)

{ FNwrite-host "Label ještě neexistuje!" 


if ($output[10] -eq "") {$output[10] = $output[06] }
if ($output[11] -eq "") {$output[11] = $output[07] }

#
#  Tvořím nový label:
# 
# Když AIP Sablona neexistuje - Tak se otestuje se zdali je Master nebo SUBordinate
if ($tartTransskriptLabelu -eq $true) {

New-Item -ItemType Directory -Force -Path "$scriptpath\Labely_log" 


Start-Transcript -path ("$scriptpath\Labely_log\AIPLabel-"+$output[0]+".log") -Force

}

        if ($output[13] -notlike "Subordinate*")  { FNwrite-host("Vytvari se MASTER Label"); write-host "-" $output[0] -ForegroundColor Green
        
        if ($WriteTemplate -eq $true) {
        NEW-Label -Name $output[0] -DisplayName $output[8] -tooltip $output[10] -Comment $output[13] 
        [Bool]$novylabel = 1
        # Když nová hodnota, tak se bude pokračovat i dale
        }
                }

        if ($output[13] -like "Subordinate*"){      FNJmenoRadku("Vytvari se SUBLabel"); write-host    "-" $output[2] -ForegroundColor Green
           [Bool]$SubLabel = 1
           $ParentLabel = $output[0].Substring(0,6) 
           $Parent = get-label | select Name | where {$_.Name -eq $ParentLabel}
           
           If ($Parent.Name -ne $ParentLabel)  { FNJmenoRadku("SUBlabel NEEXISTUJE !! "); write-host    "- ERROR" $ParentLabel -ForegroundColor Red;[Bool]$ChybiTemplate = 1} 
           If ($Parent.Name -eq $ParentLabel ) {      

           
                        # $ParentLabel = '"'+$ParentLabel+'"'
                        $ParentLabelProority = Get-label -Identity $ParentLabel | select Priority
            
                        if ($runwithdebugg -eq $true) { FNJmenoRadku("Parent Label Priority") ; write-host "-"$ParentLabelProority.Priority -ForegroundColor White }
                        
                        # $SubLabelProority = $ParentLabelProority.Priority -10

                            FNJmenoRadku("Parent Label je");            write-host    "-" $ParentLabel -ForegroundColor White
                            FNJmenoRadku("Vytvářím nově AIP Label:"); write-host    "-" $output[0]   -ForegroundColor White
                
                            
                            if ($WriteTemplate -eq $true) {

                            NEW-Label -Name $output[0] -DisplayName $output[8] -tooltip $output[10] -Comment $output[13] -ParentId ($ParentLabel)
                            [Bool]$novylabel = 1
                            # PO vytvoření nového labelu musím načíst nově labely
                            
                            $AIPExistujiciLabely = get-label | select Name
                            
                            }
            
        }        
        }
 }
 

 if ($vysledek.count -eq 1) { FNwrite-host "Label již existuje." }
 

}

Function FNNastaveniLabelu($radek) 
{

if ($runwithdebugg -eq $true) { write-host "DEBUGG: Nastaveni parametru existujicicho Labelu" }

<#################################################################################################
###                                                                                            ###
###                                                                                            ### 
###                          NASTAVNOVANI RMS Template setting                                 ### 
###                                                                                            ### 
###                                                                                            ###  
#################################################################################################> 

FNJmenoRadku("[ Nastavuji Displayname sablony ]"); fnwrite-host  $output[8] 


# overit existenci DisplayName
$AIPExistujiciDisplayname = get-label -identity $output[0] | select Displayname 

FNJmenoRadku("[ Displayname sablony           ]")
#; write-host $AIPExistujiciDisplayname.DisplayName  -ForegroundColor Green


# Vysledek overeni jedinecnosti Displayname
if ($AIPExistujiciDisplayname.DisplayName  -ne $output[8] -and $AIPExistujiciDisplayname.DisplayName  -gt "") 
{

$AIPExistujiciDisplayname2 = get-label | select name,displayname | where {$_.Displayname -eq $AIPExistujiciDisplayname.DisplayName}
Write-host "Konfliktni DisplayName! " $output[8]", patří k Labelu: "$AIPExistujiciDisplayname2.name -f red

Write-host "Přepisuji Displayname " $output[8]", patří k Labelu: "$AIPExistujiciDisplayname.name -f red
set-Label -Identity $output[0] -DisplayName $output[8] 


}

else


{
Write-host "DisplayName OK:"  $AIPExistujiciDisplayname2.Name " = Label: " $output[0]



    if ($REWriteTemplatestart -le 1 -and $REWriteTemplatekonec -ge 1 ) 
    {
    # Nastavuji Prioritu
    FNJmenoRadku("Priorita: "); write-host  $output[1] -ForegroundColor White


    # Dodělat prioritu přes Multi Array
    #
    #   Label ID 01, Priotiry
    #   label ID 02, Priotity
    #
    #  Lab

    # Priorita se nenastavuje. 
    # if ($REWriteTemplate -eq $true) {Set-Label -Identity $output[0] -Priority $output[1]}

    }


    if ($REWriteTemplatestart -le 8 -and $REWriteTemplatekonec -ge 14 ) 
    {


    FNJmenoRadku("Locale EN"); fnwrite-host ($output[8] +" - " + $output[10])
    Set-Label -Identity $output[0] -LocaleSettings ('{"localeKey":"DisplayName","Settings":[{"Key":"en-us","Value":"'+$output[8]+'"}]}')
    Set-Label -Identity $output[0] -LocaleSettings ('{"localeKey":"tooltip","Settings":[{"Key":"en-us","Value":"'+$output[10]+'"}]}')

    FNJmenoRadku("Locale CZ"); fnwrite-host ($output[9] +" - " + $output[11])
    Set-Label -Identity $output[0] -LocaleSettings ('{"localeKey":"DisplayName","Settings":[{"Key":"cs-cz","Value":"'+$output[9]+'"}]}')
    Set-Label -Identity $output[0] -LocaleSettings ('{"localeKey":"tooltip","Settings":[{"Key":"cs-cz","Value":"'+$output[11]+'"}]}')
    }


    if ($REWriteTemplatestart -le 12 -and $REWriteTemplatekonec -ge 12 ) 
    {
    # Nastavuji nové šabloně barvu Color (of a label)
    FNBarva($output[12])
    FNJmenoRadku("Barva: "+$output[12]); write-host  "-" $barva -ForegroundColor White
    if ($REWriteTemplate -eq $true) {Set-Label -Identity $output[0] -AdvancedSettings @{Color="$barva"}}
    }



     if ($REWriteTemplatestart -le 2 -and $REWriteTemplatekonec -ge 2 ) 
    {
    FNJmenoRadku( $Output1[2] ); write-host  $output[2]  -ForegroundColor Yellow
    # Obsahuje sablona status Disabled? 
    if ($output[2] -ne "on" ) { 
    $parametr = ('{"Type":"applycontentmarking","SubType":"header","Settings":[{"Key":"disabled","Value":"true"}]}')
    write-host -Identity $output[0] -LabelActions ($parametr) -ForegroundColor White 
    write-host "Appliing Disabled State" -ForegroundColor Yellow 
    if ($REWriteTemplate -eq $true) {Set-Label -Identity $output[0] -Disabled 1 }
    }
    }

    if ($REWriteTemplatestart -le 14 -and $REWriteTemplatekonec -ge 18 ) 
    {
        FNJmenoRadku($Output1[14]); write-host  $output[14]  -ForegroundColor Yellow
    # Obsahuje sablona HEADER? 
    if ($output[14] -eq "ON" ) { 
    if ($output[14+2] -is [int] ) { $output[14+2] = "10" }
    if ($output[14+3].count -gt 1 ) { $output[14+3] = "Calibri" }
    fnbarva($output[14+4])
    $output[14+4] = $Script:barva


    $parametr = ('{"Type":"applycontentmarking","SubType":"header","Settings":[{"Key":"disabled","Value":"false"},{"Key":"fontsize","Value":"'+$output[14+2]+'"},{"Key":"text","Value":"'+$output[14+1]+'"},{"Key":"fontcolor","Value":"'+$output[14+4]+'"},{"Key":"fontname","Value":"'+$output[14+3]+'"},{"Key":"margin","Value":"25"},{"Key":"placement","Value":"Header"},{"Key":"alignment","Value":"'+$output[14+5]+'"}]}')
    if ($runwithdebugg -eq $true) { write-host -Identity $output[0] -LabelActions ($parametr) -ForegroundColor Gray }
    FNJmenoRadku( "HEADER "+$Output1[14] ); write-host  $output[15]  -ForegroundColor Yellow
    if ($REWriteTemplate -eq $true) {SET-Label -Identity $output[0] -LabelActions ($parametr)}
    }
    }

    if ($REWriteTemplatestart -le 20 -and $REWriteTemplatekonec -ge 24 ) 
    {
    FNJmenoRadku( $Output1[20] ); write-host $output[20]  -ForegroundColor Yellow
    # Obsahuje sablona Footer? 
    if ($output[20] -eq "ON" ) {
    if ($output[20+2] -is [int] ) { $output[20+2] = "10" }
    if ($output[20+3].count -gt 1 ) { $output[20+3] = "Calibri" }
    fnbarva($output[20+4])
    $output[20+4] = $Script:barva


    $parametr = ('{"Type":"applycontentmarking","SubType":"footer","Settings":[{"Key":"disabled","Value":"false"},{"Key":"fontsize","Value":"'+$output[20+2]+'"},{"Key":"text","Value":"'+$output[20+1]+'"},{"Key":"fontcolor","Value":"'+$output[14+4]+'"},{"Key":"fontname","Value":"'+$output[20+3]+'"},{"Key":"margin","Value":"25"},{"Key":"placement","Value":"Footer"},{"Key":"alignment","Value":"'+$output[20+5]+'"}]}')
    write-host -Identity $output[0] -LabelActions ($parametr) -ForegroundColor White 
    FNJmenoRadku( "FOOTER "+$Output1[20] ); write-host  $output[21]  -ForegroundColor Yellow
    if ($REWriteTemplate -eq $true) {SET-Label -Identity $output[0] -LabelActions ($parametr)}
    }
    }

    if ($REWriteTemplatestart -le 26 -and $REWriteTemplatekonec -ge 30 ) 
    {
    FNJmenoRadku( $Output1[26] ); write-host $output[26]  -ForegroundColor Yellow
    # Obsahuje sablona WATERMARK? 
    if ($output[26] -eq "ON" ) {
    if ($output[26+2] -is [int] ) { $output[26+2] = "10" }
    if ($output[26+3].count -gt 1 ) { $output[26+3] = "Calibri" }
    fnbarva($output[26+4])
    $output[26+4] = $Script:barva


    $parametr = ('{"Type":"applywatermarking","SubType":null,"Settings":[{"Key":"disabled","Value":"false"},{"Key":"fontsize","Value":"'+$output[26+2]+'"},{"Key":"text","Value":"'+$output[26+1]+'"},{"Key":"fontcolor","Value":"'+$output[14+4]+'"},{"Key":"fontname","Value":"'+$output[26+3]+'"},{"Key":"layout","Value":"Diagonal"}]}')
    write-host -Identity $output[0] -LabelActions ($parametr) -ForegroundColor White 
    FNJmenoRadku( "WATERNARK "+$Output1[26] ); write-host  $output[27]  -ForegroundColor Yellow
    if ($REWriteTemplate -eq $true) {SET-Label -Identity $output[0] -LabelActions ($parametr)}
    
    }
    }



    #
    #   xxxx  x     x  xxx
    #   x   x xx   xx x   x    
    #   xxxx  x x x x xxxx                   
    #   x   x x  x  x     x
    #   x   x x     x x   x       
    #   x   x x     x  xxx
    #
    ###############################################################################################################
    #  Vypisuji paramtry pro RMS (Pokud exituji)
    ###############################################################################################################
    $predtext = "[RMS]"  
    $output2=""   

    if ($runwithdebugg -eq $true) { write-host "DEBUGG: FNNastaveniLabelu - RMS" }

    # Obsahuje sablona REMOVE RMS? 
    # Not configured
    # Remove Protection
    # R00006S002

    
    #RMS REMOVE PROTECTION

        if ($output[33] -eq "Remove Protection" ) { 
        write-host "Odebírám RMS PERMISSION :" -f Magenta
        write-host "Remove RMS Template :" $output[33] -ForegroundColor Yellow 

        $parametr = ('{"Type":"encrypt","SubType":null,"Settings":[{"Key":"protectiontype","Value":"removeprotection"},{"Key":"disabled","Value":"false"}]}')
        FNJmenoRadku( $Output1[33] ); FNWrite-Host ($output[33])
        if ($REWriteTemplate -eq $true) { 
        FNJmenoRadku("_Remove Protection"); FNWrite-Host ("- "+$parametr)
        SET-Label -Identity $output[0] -LabelActions ($parametr) }
        }
    
     


if ($output[33] -like "Apply Protection" ) 
{
    write-host "NASTAVUJI RMS PERMISSION :" -f Magenta
    #
    #  Na šablonu se nastavuje Šifrování, tvořím tedy politiku pro šifrování
    #

    if ($REWriteTemplatestart -le 36 -and $REWriteTemplatekonec -ge 38 ) 
    {

    if ($output[36] -like "*user*" -and $output[36] -like "*permissions*") 
    {

    FNJmenoRadku("Set permissions for documents and emails")
    write-host $output[36] -ForegroundColor Yellow   

    # Nastaveni hodnoty pro In Outlook apply Do Not Forward
    if ($output[37] -ne "x" ) { $output[37]="true"}
    else { $output[37]="false" }

    # Nastaveni hodnoty - ASI - In Word, Excel, PowerPoint and File Explorer prompt user for custom permissions 
    if ($output[38] -ne "x" ) { $output[38]="true"}
    else { $output[38]="false" }  


    #  Prikladový radek, pro Skript se odebírají jedny složené závorky
    #             {{"Type":"encrypt","SubType":null,"Settings":[{"Key":"disabled","Value":"false"},{"Key":"protectiontype","Value":"userdefined"},{"Key":"donotforward","Value":"true"},{"Key":"promptuser","Value":"true"}]}}
    
    
    $parametr = ('{"Type":"encrypt","SubType":null,"Settings":[{"Key":"disabled","Value":"false"},{"Key":"protectiontype","Value":"userdefined"},{"Key":"donotforward","Value":"'+$output[37]+'"},{"Key":"promptuser","Value":"'+$output[38]+'"}]}')
    
    if ($runwithdebugg -eq $true) { write-host "Prováním zápis nastavení práv...." $parametr -f Gray} 
    
    Set-Label -Identity $output[0] -LabelActions $parametr
    }
    }


    # if (36 -ge $REWriteTemplatestart -and 43 -le $REWriteTemplatekonec ) 
}
    IF ( $REWriteTemplatestart -le 39 -and $REWriteTemplatekonec -ge 40)   
    {

   
            FNJmenoRadku("RMS Parametr: Set permissions"); 
            # Kdyz jsou definovany hodnoty pro SET USER na šabloně
            if ($output[36] -like "*Set permissions*" ) { 

             
                  $parametr=""
                  $prava = $output[44]  # Když už jsou práva definována
                  if ($output[43] -eq "Custom")    {$prava = $output[44]}
                  if ($output[43] -eq "Co-Owner")  {$prava = "VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,EDITRIGHTSDATA,EXPORT,OBJMODEL,OWNER"}
                  if ($output[43] -eq "Co-Author") {$prava = "VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,OBJMODEL"}
                  if ($output[43] -eq "Reviewer")  {$prava = "VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,REPLY,REPLY ALL,FORWARD,OBJMODEL"}
                  if ($output[43] -eq "Viewer")    {$prava = "VIEW,VIEWRIGHTSDATA,OBJMODEL"}
  
              $parametrRMS = '"'+ $prava -replace ',','","' 
              $parametrRMS = $parametrRMS +'"'

                  $parametr = $prava -replace " ",""
                  $parametr = '\"'+$parametr
                  $parametr = $parametr + '\'
                  # $parametr = $parametr -replace '\/','"'
  
                   if ($runwithdebugg -eq $true) { write-host "Práva...." $parametr -f Gray} 







    
                if ($REWriteTemplate -eq $true -and $output[43] -ne "x") { 
                        if ($runwithdebugg -eq $true) { write-host "Prováním zápis nastavení práv...:" $parametrrights -f Gray} 
                           
                      $parametrrights = '{"Type":"encrypt","SubType":null,"Settings":[{"Key":"protectiontype","Value":"userdefined"},{"Key":"rightsdefinitions","Value":"[{\"Identity\":\"'+$output[42]+'\",\"Rights\":'+$parametr+'"}]"}]}'

                     FNJmenoRadku("_UserCustom Rights to:"); write-host $output[42] -ForegroundColor Yellow
  
                     Set-Label -Identity $output[0] -LabelActions $parametrrights 


                     if ($REWriteTemplate -eq $true -and $output[43] -ne "x") { 
                     if ($runwithdebugg -eq $true) { write-host "Prováním zápis nastavení práv...." $parametr -f Gray} 
                     
                     

                   # Zjištuji zdali exstuje již RMS šablona

                try 
                { 
                $searchtext = '*'+$output[5]+'*'                # $searchtext = '*CEZ-DGR*'
                $rms  = $AIPExistujiciRMSTemplates |  where {$_.Names -like $searchtext}   # -like "*TEST*"                }
                catch 
                {
                  Write-Host "Nemohu načít Labely RMS. zkuste prihlášení do Azure portálu:"
                  Write-Host $_.ScriptStackTrace
                  end

                }                finally                {                }                $rms2 = $rms.TemplateId.Guid                FNJmenoRadku("_Found RMS Template for OU:" + $output[5] + " "); write-host $rms2 -ForegroundColor Yellow                          # Remove-Variable labely -ErrorAction SilentlyContinue
# Get-AipServiceTemplate -TemplateId 8f190168-353c-4754-b472-f438ef20f93b
# Import-AipServiceTemplate
# Export-AipServiceTemplate -TemplateId 8f190168-353c-4754-b472-f438ef20f93b -path d:\test\testRMStemplate.xml




             # Když neexisutje již RMS šablona

       

             if ($rms2 -like "") {
             $parametrrights =  '{"Type":"encrypt","SubType":null,"Settings":[{"Key":"protectiontype","Value":"template"},{"Key":"disabled","Value":"false"},{"Key":"templatearchived","Value":"True"},{"Key":"rightsdefinitions","Value":"[{\"Identity\":\"'+$output[42]+'\",\"Rights\":'+$parametr+'"}]"}]}'
             }
             else {
             # RMS sablona existuje a tam se na NI label nalinkuje      # {"Key":"templateid","Value":"+$rms.templateID+"},{"Key":"linkedtemplateid","Value":"+$rms.templateID+"}   {"Key":"linkedtemplateid","Value":"'+$rms2+'"}
             $parametrrights =  '{"Type":"encrypt","SubType":null,"Settings":[{"Key":"protectiontype","Value":"template"},{"Key":"templateid","Value":"'+$rms2+'"},{"Key":"linkedtemplateid","Value":"'+$rms2+'"},{"Key":"disabled","Value":"false"},{"Key":"templatearchived","Value":"True"},{"Key":"rightsdefinitions","Value":"[{\"Identity\":\"'+$output[42]+'\",\"Rights\":'+$parametr+'"}]"}]}'
       
             }

                      $parametrrights                      
                     Set-Label -Identity $output[0] -LabelActions $parametrrights 

              }
              }

    }
   }   
  }  
   
   
     
#
# DALSI RMS PARAMETRY - OVERIT jejich nastavení zdali je ok !!!! 
#

  if ($output[33] -like "Apply Protection" ) 
{

    if ($REWriteTemplatestart -le 39 -and $REWriteTemplatekonec -ge 40 ) 
        {


         # Kdyz jsou definovany hodnoty -ContentValidityDuration
         if ($output[39]  -ne "x" ) { 
         $parametr2 = $output[39] 
         if ($output[39]  -eq "never" ) { $parametr2 = "never"}
         if ($output[39]  -eq "bydate" )  { $parametr2 = "0" }
         if ($output[39]  -eq "bydays" )  {  }

         $parametrrights2 = '{"Type":"encrypt","SubType":null,"Settings":[{"Key":"contentexpiredondateindaysornever","Value":"'+$parametr2+'"}]}'

         FNJmenoRadku("_-contentexpiredondateindaysornever"); write-host $parametr2 -ForegroundColor White
         if ($REWriteTemplate -eq $true) { SET-Label -Identity $output[0] -LabelActions $parametrrights2 }
         }

         # Kdyz jsou definovany hodnoty  -ContentExpirationOption  (Never, OnDate, AfterDays)
         if ($output[40]  -ne "x" ) { 
         $parametr2 = $output[40] 
         if ($output[40]  -eq "never" ) { $parametr2 = "-1"}
         if ($output[40]  -eq "allways" ) { $parametr = "0" }
         if ($output[40]  -eq "bydays" ) {  }
         $parametrrights2  = '{"Type":"encrypt","SubType":null,"Settings":[{"Key":"offlineaccessdays","Value":"'+$parametr2+'"}]}'

         FNJmenoRadku("_-offlineaccessdays"); write-host $parametr2 -ForegroundColor White
         if ($REWriteTemplate -eq $true) { SET-Label -Identity $output[0] -LabelActions $parametrrights2  }
         }
         }

  
     }


     
     # Label Custom Properties
              if ($REWriteTemplatestart -le 45 -and $REWriteTemplatekonec -ge 45 )
              {
        

          FNJmenoRadku("Setting Advanced Settings: for" + $output[5] + " "); write-host $output[0] -ForegroundColor Yellow 
        

          $myLdn = $output[0]
          $myOrgID = $output[5]



            Switch -Wildcard ($myLdn) { # switch 1

                'Public-*' {
                    [string]$myOrgID = ""
                    $myOrgID = $myLdn.Replace("Public-","")
                    $asHT = @{}
                    $asHT.Add("customPropertiesByLabel",(ConvertTo-Json("DocumentClasification,Veřejné", ("CEZ_DLP,CEZ:" + $myOrgID + ":D"))))
                    $asHT.Add("labelByCustomProperties",("DocTag D 2 MIP Public " + $myOrgID + ",CEZ_DLP,^CEZ:" + $myOrgID + ":D"))
                    Set-Label -Identity $myLn -AdvancedSettings $asHT -Verbose
                    Write-Host ("D=" + $myOrgID + "=" + $PSItem) -ForegroundColor Green
                    sleep 2
                    break
                }

                'Internal-*' {
                    [string]$myOrgID = ""
                    $myOrgID = $myLdn.Replace("Internal-","")
                    $asHT = @{}
                    $asHT.Add("customPropertiesByLabel",(ConvertTo-Json("DocumentClasification,Interní", ("CEZ_DLP,CEZ:" + $myOrgID + ":C"))))
                    $asHT.Add("labelByCustomProperties",("DocTag C 2 MIP Internal " + $myOrgID + ",CEZ_DLP,^CEZ:" + $myOrgID + ":C"))
                    Set-Label -Identity $myLn -AdvancedSettings $asHT -Verbose
                    Write-Host ("C=" + $myOrgID + "=" + $PSItem) -ForegroundColor Green
                    sleep 2
                    break
                }

                {($PSItem -like 'Protected-*') -and ($PSItem -notlike "*_*")} {
                    Write-Host ("B0=" + $PSItem) -ForegroundColor Cyan
                    sleep 2
                    break
                }

                {($PSItem -like 'Protected-*') -and ($PSItem -like "*-encryption_for_CEZ_Group")} {
                    [string]$myOrgID = ""
                    $myOrgID = $myLdn.Replace("Protected-","")
                    $myOrgID = $myOrgID.Replace("-encryption_for_CEZ_Group","")
                    $asHT = @{}
                    $asHT.Add("customPropertiesByLabel",(ConvertTo-Json("DocumentClasification,Chráněné", ("CEZ_DLP,CEZ:" + $myOrgID + ":B"))))
                    $asHT.Add("labelByCustomProperties",("DocTag B 2 MIP Protected " + $myOrgID + ",CEZ_DLP,^CEZ:" + $myOrgID + ":B"))
                    Set-Label -Identity $myLn -AdvancedSettings $asHT -Verbose
                    Write-Host ("B1=" + $PSItem) -ForegroundColor Cyan
                    sleep 2
                    break
                }

                {($PSItem -like 'Protected-*') -and ($PSItem -like "*-encryption_custom_permissions")} {
                    [string]$myOrgID = ""
                    $myOrgID = $myLdn.Replace("Protected-","")
                    $myOrgID = $myOrgID.Replace("-encryption_custom_permissions","")
                    $asHT = @{}
                    $asHT.Add("customPropertiesByLabel",(ConvertTo-Json("DocumentClasification,Chráněné", ("CEZ_DLP,CEZ:" + $myOrgID + ":B"))))
                    Set-Label -Identity $myLn -AdvancedSettings $asHT -Verbose
                    Write-Host ("B2=" + $PSItem) -ForegroundColor Cyan
                    sleep 2
                    break
                }

                {($PSItem -like 'Protected-*') -and ($PSItem -like "*-no_encryption")} {
                    [string]$myOrgID = ""
                    $myOrgID = $myLdn.Replace("Protected-","")
                    $myOrgID = $myOrgID.Replace("-no_encryption","")
                    $asHT = @{}
                    $asHT.Add("customPropertiesByLabel",(ConvertTo-Json("DocumentClasification,Chráněné", ("CEZ_DLP,CEZ:" + $myOrgID + ":B"))))
                    Set-Label -Identity $myLn -AdvancedSettings $asHT -Verbose
                    Write-Host ("B3=" + $PSItem) -ForegroundColor Cyan
                    sleep 2
                    break
                }

                default {Write-Host ("Label " + $myLdn + " was skipped.") -ForegroundColor Yellow}

            } # switch 1






        }



















  
if ($Starttransktiptlabelu -eq $true) { 
Stop-Transcript
 }
 write-host "Konec bloku nastaveni Labelu"
  }

#   Konec RMS Template Settings
 



###############################################################################################################
#
#
#  START PROGRAMU
#
#
###############################################################################################################


<#################################################################################################
# Program zpracovava RADEK po RADKU v CSV 


$Output[0]
$Output[1]
$Output[2]
$Output[3]


#################################################################################################> 
#
#  Tady v tom bloku se budeprovádet program tak dlouho, dokud na konci nebude naplněna hodnota
#  Provedeny  pocer radku CSV TEST + všechny OU
#

#  Probeh Programu
#  1 - Program nejprce zpracuje obsah naplnenoho XLS Labels z file 1 
#  2 - Program provede pocet opakovani OPACKO na všechny OU z File2

# Zpracovavam CLS Labels

$celkem = ((($linesoncsv2+1)*$opackocelkem))+$linesoncsv
$provadimakci = 0

# if ($zpracujiOU -eq 1) {$celkem = (($linesoncsv2*($opacko*$opackocelkem))+$linesoncsv)}


if ($Skoncinaradku -gt 0) {$linesoncsv = $Skoncinaradku}

For ($r=$Startujnaradku; $r -le $linesoncsv; $r++ ) 
{
# $labely="TEST"


$provadimakci = $provadimakci +1

   
GetCSVLine ($r)  # Načítám data řádku.
FNHeaderProgramu
FNListHodnot($r)
FNVypishodnot
# $Output[0]
write-host "Zpracovávám První CSV, radek $r" -F Magenta

FNTvorbaLabelu($r)
FNNastaveniLabelu($r)

FNEndRadekPause("Pokračovaní")


}



#
#  Zpracovava se OU xls
# 
if ($orgstruktury -eq $true) 
{

# Výpočet čísla pro pokračujici Labelname
$labelno = (($linesoncsv/$opackocelkem))*($opackocelkem/2) 
$labelsubno = 0


For ($hod=0; $hod -le $linesoncsv2; $hod++ ) {
$ou = $hod


#
#    Tady se msuí upravovat Label Name protože musí navazovat na ten XLS a pokračovat v číslování Lxxxx a LxxxxSxxx
# 

# Když zpracovává nový řádek, tak bue načítat další oddělení CEZu z další tabulky
## Replacement jmen v sablonach L0000x za L0000+cykus + opacko
## Replacement jmen v sablonach L0000xS001 za L0000+cykus + opacko



    For ($opacko=1; $opacko -le $opackocelkem ; $opacko++ ) {
    
    #
    #    Tady se musí nahrazovat jméno TEST za OU
    #
    $labely = $nactenecsv2[$hod].Prefix 
    $emailGroupScope = $nactenecsv2[$hod].GroupScope


    GetCSVLine ($opacko)  # Načítám data řádku. (tady by se mělo načítat vždy řádek TEST 1-6)
  # FNListHodnot($opacko)
    $nahrazuji =  "TEST"

    FNHeaderProgramu

   
   # Bude se zpracovávat i list s OU
   if ($zpracujiOU -eq $true) {

        write-host "Zpracovávám Druhý CSV, stav: $stav  Labely: $nahrazuji >> $labely - sablona: $opacko \ 6  " -F Magenta
    
        if ($emailGroupScope -eq "Universal" ) {

        write-host "Email - Universal" 


            FNListHodnot($opacko)
                    $Output[0] = $JmeloLabelu

                # for ($i = 1; $i -lt $pocethodnot; $i++) {
                for ($i = 1; $i -lt $pocethodnot; $i++) {

                 $output[$i] = $output[$i] -replace $nahrazuji,$labely
                             }

                # $output[5] = $output[5] -replace $output[5],$labely



                    if ($output[13]-like "Subordinate*")  
                    # Tak se jedna o sublabel
                    {
                    $labelsubno ++
                    $output[0] = $output[0]+"S"+$labelsubno.tostring("000")
                    Write-Host "Sub-Label" $output[0]
                
                    }
                    else
                    {
          
                    # Tak se jedna o Label
                    $labelsubno = 0
                    $labelno ++
                    $JmeloLabelu = "L"+$labelno.ToString("00000")
                     # $output[0] = "P"+$r.ToString("00000")
                 
                    $Output[0] = $JmeloLabelu
                    Write-Host "Master-Label" $Output[0]
                
                    }
                
                Write-Host "ZAPISUJI OU $hod  -  $Zacninaoucislo " 
                 

                    # Když chci zacínat až na nějakém řádku OU, tak se se zápisem čeká
                    if ($hod -ge $Zacninaoucislo) {
                        FNVypishodnot
                        FNTvorbaLabelu(0)
                        FNNastaveniLabelu(0)
                    
                    }




            
            }
        }

    }

    FNEndRadekPause("Pokračovaní")
    Stop-Transcript -ErrorAction SilentlyContinue
    if ($tartTransskriptLabelu -eq $true) {Stop-Transcript -ErrorAction SilentlyContinue}

}
 
}

 



###############################################################################################################
#
#
#  KONEC PROGRAMU
#
#
###############################################################################################################

# Uklizím po sobě proměnné

# Remove-Item *.csv

FNListExistingAzureLabels

 
FNWrite-host ("===============================================================================================")
$predtext = "Počet Chyb ve skriptu: "+$Error.Count + " "

if ($error.Count -gt 0) {$Error}




FNJmenoRadku ("="); write-host "`n"

# END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END

write-host "[END of SCRIPT `t`t KONEC PROGRAMU `t`t END of SCRIPT] " -F Gray -BackgroundColor Black

FNEndRadekPause


Stop-Transcript -ErrorAction SilentlyContinue

 
exit # END END END END END END END END END END END END END END END END END END END END END END END END END END END END END
