<#
################################################################################################
 2020-07-01 - 13:00

 Backuping AIP UL
 Install-Module -Name ImportExcel

 Z Excelu se vytovří CSV soubory, a načítá se Policy list


 očekávané vstupy o policy: 

#> 
################################################################################################



CLS
Clear-Host
Remove-Variable * -ErrorAction SilentlyContinue
$Error.clear()

<#
# Prihlášení do PS EOA
#>

$UserCredential = Get-Credential -UserName vlada@acinfraseclab.onmicrosoft.com -Message "Connect to Azure AIP"
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.compliance.protection.outlook.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
Import-PSSession $Session  ###TOHLE JE KLICOVE PRO AIP Script prikazy 

#  PROHLASENI DO AIP SERVICE
$AdminCredentials = Get-Credential "vlada@acinfraseclab.onmicrosoft.com"
Connect-AipService -Credential $AdminCredentials 




<##################################################################################
#                DEFINOVANI PROMMENNYCH PRO BEH PROGRAMU
##################################################################################>

# CESTA KDE JE SPUSTEN SKRIP
$scriptpath = Split-Path -parent $MyInvocation.MyCommand.Definition
$datum = date -Format HH:mm:ss

# Definovani XLS Souboru 
$excelFileName = "CEZ-AIP-Label-Production-Final_u3.xlsx"
$filter1 = "policy"
$filter2 = "orgStructure"

[bool]$runwithpause    = 0          # True/False - True = program nebude cekat na mačkání mezerníku po krocích 
[bool]$runwithdebugg   = 1          # True/False - True = program bude vypisovat vice detailu 
$Startujnaradku        = 0          # 0 je výchozí hodnota radku na kterem se zacina, vyssi cisla se pouzivaji pro ladení prograamu

[Bool]$WritePolicyTemplate =    0   # 1 - ZAPISOVACI REZIM  !!!
[Bool]$REWritePolicyTemplate =  0   # 1 - PREPISOVACI REZIM !!!


#  $JednaPolitikaRadku          =  6   # Bez detecke skriptu - kolik ma CSV soubor jíz nadefinovanch labelu pro jednu politiku
$vzdalenost = 60
$opacko=1


<#################################################################################################
#   
#  Generuji z XLS -->  CSV soubory
#   
#################################################################################################>



 Function ExportWSToCSV ($excelFileName, $csvLoc, $filter){
 



 # Funkce exportuje CSV na základe filteru : (*neco*)
    $excelFile = ($csvLoc +"\"+ $excelFileName)
    Write-host "Converting XML file: $csvLoc\$excelFileName" -f Yellow

    $E = New-Object -ComObject Excel.Application 
    $E.Visible = $false
    $E.DisplayAlerts = $false
    $wb = $E.Workbooks.Open($excelFile)

        foreach ($ws in $wb.Worksheets)
        {
            $n = $excelFileName + "_" + $ws.Name
            if ($n -like "*$filter*" ) {
            Write-host "Converting... XML list to CSV: $n .csv" -f Yellow
            $ws.SaveAs($csvLoc +"\"+ $n + ".csv", 6)
       }
           }
    $E.Quit()
}

$filter=$filter1
# Oveřuji existenci csl listu, pokud není generuji si ho z excelu
$filename = Get-ChildItem "*$filter*.csv" -Path $scriptpath -name

if ($filename.count -eq 0) {
write-host "Vytvářím z XLS jednotlivé listy jako CSV soubory CSV...."
ExportWSToCSV -excelFileName $excelFileName -csvLoc $scriptpath -filter $filter
$filename = Get-ChildItem "*$filter*.csv" -Path $scriptpath -name
}


# NACITAM DATA z CSV - Vznika hlavni programova promenna
$nactenecsv = Import-Csv -Path $scriptpath\$filename  -Encoding Default -Delimiter ','
$linesoncsv = $nactenecsv.Count -0


$filter=$filter2
# Oveřuji existenci csl listu, pokud není generuji si ho z excelu
$filename = Get-ChildItem "*$filter*.csv" -Path $scriptpath -name

if ($filename.count -eq 0) {
write-host "Vytvářím z XLS jednotlivé listy jako CSV soubory CSV...."
ExportWSToCSV -excelFileName $excelFileName -csvLoc $scriptpath -filter $filter
$filename = Get-ChildItem "*$filter*.csv" -Path $scriptpath -name
}

# NACITAM DATA z CSV - Vznika hlavni programova promenna
$nactenecsv2 = Import-Csv -Path $scriptpath\$filename  -Encoding Default -Delimiter ','
$linesoncsv2 = $nactenecsv2.Count -1
$ou = 0

<#
2-0 : Policy_ID (generated by SkČ) .................................................... - P00001
2-1 : Policy name ..................................................................... - ICT-Labels
2-2 : Policy description .............................................................. - ICT-Labels-General, Last modified 20191126
2-3 : The policy applies to ........................................................... - cez_mip_users_ict@cezdata.onmicrosoft.com
2-4 : Label list (reference) .......................................................... - L00001,L00002,L00003,L00003S001,L00003S002,L00003S003
2-5 : Title ........................................................................... - x
2-6 : Tooltip ......................................................................... - x
2-7 : Select the default label ........................................................ - NONE
2-8 : Send logging data to Azure Information Protection analytics ..................... - ON
2-9 : All documents and emails must have a label ...................................... - OFF
2-10 : Users must provide justification to set a lower classification label, remove a l  - ON
2-11 : For email messages with attachments, apply a label that matches the highest clas  - Automatic
2-12 : Add policy tip describing to users the reasons for applying this label .......... - Tento email byl automaticky klasifikován jako / This email was automatically lab
2-13 : Display the Information Protection bar in Office apps ........................... - ON
2-14 : Add Do Not Forward button to the Outlook ribbon ................................. - ON
2-15 : Make the custom permissions option available for users .......................... - OFF
2-16 : "Provide a custom URL for the Azure Information Protection client ""Tell me more  - <blank>
#>

<#  -----------------------------------------------------------------------------------
#  [                                 FUNKCE PROGRAMU                                  ]
    ----------------------------------------------------------------------------------- #>
############<<<<########################################################>>>>############

<#  -----------------------------------------------------------------------------------
#  [              ZAKLADNI PREZENTACE PROMMENYCH PRED SPUSTENIM PROGRAMU               ]
    ----------------------------------------------------------------------------------- 
############<<<<#####################################################################>


function FNBarva($BarvaIn) {
$barva = "#000000" # Default Color for new Teplates
# if ($BarvaIn -ne "x") {$Script:barva  = "#"+[Convert]::ToString([System.Drawing.ColorTranslator]::ToWin32([System.Drawing.Color]::($BarvaIn)), 16).PadLeft(6, '0') }
if ($BarvaIn -ne "x") {$Script:barva = "#" + [System.Drawing.Color]::($BarvaIn).R.ToString("x2") + [System.Drawing.Color]::($BarvaIn).G.ToString("x2") + [System.Drawing.Color]::($BarvaIn).B.ToString("x2") }
}

function FNJmenoRadku($JmenoRadku) {

$BarvaRadku ="Yellow"
if ($predtext -like "Heade*") {$BarvaRadku ="White"}


IF ($JmenoRadku.Length -eq "")       {     write-host -nonewline; $Script:spaces = '.' * ($vzdalenost)}
# Vykresluje jeden znak
IF ($JmenoRadku.Length -eq 1)           {$spaces = "$JmenoRadku" * ($vzdalenost) 
                                           Write-host $predtext$spaces -ForegroundColor Yellow -NoNewline }
IF ($JmenoRadku.Length -gt 1)           {  Write-host $predtext -ForegroundColor $BarvaRadku -NoNewline 

IF ($JmenoRadku.Length -gt $vzdalenost) {Write-host $JmenoRadku.Substring(0,$vzdalenost)"- " -ForegroundColor Yellow -NoNewline }
else
{                                          Write-host $JmenoRadku -ForegroundColor Yellow -NoNewline
                                $pocet = (($vzdalenost) - $JmenoRadku.Length)
                                $spaces = '.' * ($pocet) +" - "
                                           write-host $spaces -f gray -NoNewline }}
}


Function FNGetCSVLineVariable($cislohodnoty) {
    if ($cislohodnoty -le $pocethodnot) {
    # rozebere CSV radek na jmeno sloupce a hodnotu
    $script:Sloupec,$script:hodnota = $DatavCSV2[$cislohodnoty] -split("="),0
    $script:Sloupec = $script:Sloupec -replace "`n",""
    }
}
 
Function FNGetCSVLine ($cisloradku) {
if ($cisloradku -le $linesoncsv) {
    # rozebere CSV na radky
    $radek =  $nactenecsv[$cisloradku]

    # zajistit odebrani substringem
    $radek = $radek -replace "@{",""
    $radek = $radek -replace "}",""
    $script:DatavCSV2 = $radek -split('; ')
    $script:pocethodnot = $DatavCSV2.Count

}
}

Function FNNactiNazvyaHodnotySloupcu($text) {
$predtext = $text.tostring("00")+": "

$Output3 = @();
$Output4 = @();

for ($i = 0; $i -lt $pocethodnot; $i++)
{ 
if ($test -eq "0") {}
FNGetCSVLineVariable($i)$Output3 += $sloupec
$Output4 += $hodnota

}

# Prevod promenné z Funkce do promenne kterou mohu použít ve sktiptu
$script:output = $output4
$script:output1 = $output3

}
    
function FNWrite-Host($JmenoRadku) {

         switch ($JmenoRadku){
         OFF     {$BarvaRadku ="Gray" }
         x       {$BarvaRadku ="Gray" }
         ON      {$BarvaRadku ="Green"}
         True    {$BarvaRadku ="Green" }
         ERROR   {$BarvaRadku ="Red"}
         False   {$BarvaRadku ="Gray"}
         default {$BarvaRadku ="White"} 
         }

        if ($predtext -like "Header") {$BarvaRadku ="White"}
        if ($JmenoRadku.Length -gt $vzdalenost) { write-host (""+$JmenoRadku.Substring(0,$vzdalenost)) -F $BarvaRadku }
        else                                    { write-host (""+$JmenoRadku) -F $BarvaRadku }
}

function FNInfoHeader{
FNJmenoRadku ("Počet datových řádků v $file1 :") ; FNwrite-host $linesoncsv
FNJmenoRadku ("Počet datových řádků v $file2 :") ; FNwrite-host $linesoncsv2

$predtext = "=========="
FNJmenoRadku ("="); write-host " - " -nonewline ; FNJmenoRadku ("=");write-host ""
write-host "Kontorla!        Jmána sloupců a hodnot z druhého řádku CSV             " -f Green -b Black


$output = (Get-content $scriptpath\$file1)[2].Split(";")

for ($i = $Startujnaradku ; $i -lt $output1.Count ; $i++)
{
$predtext = ("Header "+$i.ToString("00")+" ")
FNJmenoRadku ($output1[$i]) ; FNwrite-host ($output[$i])

}
}

Function FNVypishodnot {
for ($i = 0; $i -lt $pocethodnot; $i++) {
$predtext = $i.tostring("00")+": "
FNJmenoRadku ($Output1[$i]) ; FNwrite-host ($output[$i])
}
}

Function FNEndRadekPause($text){
###############################################################################################################
### END RADEK zmackni SPACE
###############################################################################################################
if ($runwithpause -eq $true) {
  # write-host "Press Space to next Label..... " -ForegroundColor Black -BackgroundColor White
  write-host "`n" 
  $text =  'Zmáčkněte "Space" pro '+$text+' ..... '
  Read-Host -prompt $text
}
}






Function FNHeaderProgramu() {
<#################################################################################################
#
# HEADER PROGRAMU
#
# zde je možné vkládat jakékoliv udaje o pormenných programu a jejich zobrazování v prubehu
#################################################################################################>  
CLS
if ($runwithdebugg -eq $true) { write-host "DEBUGG: FNHeaderProgramu" }
  
    write-host "Průběh Programu - zpracovávaní řádků: " -f Green
    write-host " [" $r.ToString("000") "/" $linesoncsv.ToString("000") "] Labelu v základním XLS" -ForegroundColor Green 
    write-host " [" $ou.ToString("000") "/" $linesoncsv2.ToString("000") "] OU kterým se budou generovat Labely " -ForegroundColor Green
    write-host " [" $opacko.ToString("000") "/" $opackocelkem.ToString("000") "] poradí Labelu pro OU" -ForegroundColor Green
 
 $stav = ($r + ($ou * $opackocelkem)+$opacko)
 $celkem = (($linesoncsv2*$opackocelkem)+$linesoncsv)
 $proc = ($stav/$celkem)*100
 $casted = (get-date).Millisecond

    write-host " [" $stav.ToString("000") "/" $celkem.ToString("000") "] Celkem labelu  --- " $proc.ToString("000") " % " -ForegroundColor Blue


write-host "Počet hodnot z aktuálně načteného csv řádku:  "  -f Green -Nonewline
write-host "[$pocethodnot] "     -ForegroundColor Green
write-host $file2  -f Yellow

$predtext = ""
FNJmenoRadku ("="); write-host " - " -nonewline 
$predtext = "Jmena a sloupce: "
    if ( $runwithdebugg -eq 1) {FNWrite-Host ("= - === Pri Debugg se nezkracují hodnoty! ===========") }
    else                       {FNWrite-Host ("============================================================================")}




    if ($stav -gt $Skoncinaradku -and $Skoncinaradku -gt 0 ) {
    $runwithpause = 1
    FNEndRadekPause("Konec - byl dosazen limit SKONCINARADKU")
    Stop-Transcript
    exit
    
    
    }



}

Function FNTvorbaPolitiky{

<#################################################################################################
#                         Overeni zalogování do AZURE - pri New nebo SET hodnot  
#################################################################################################> 

if ([Bool]$WritePolicyTemplate -eq $true -or [Bool]$REWritePolicyTemplate -eq $true ) {
# 1 - ZAPISOVACI REZIM !!!

# Kontrola prihlašení do Azure
$jsemzalogovan = Get-PSSession | select name | FT
if ($jsemzalogovan -eq $null) {
$UserCredential = Get-Credential -UserName acseclabadmin@acinfraseclab.onmicrosoft.com -Message "Connect to Azure AIP"
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.compliance.protection.outlook.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
Import-PSSession $Session  ###TOHLE JE KLICOVE PRO EOL (MIP) COMMANDY
}
}
$AIPExistujiciPolicy = get-labelpolicy | select Guid,Name,displayname
$AIPExistujiciLabely = get-label | select Guid,Name,displayname






$predtext = "" ; FNJmenoRadku ("-"); Write-host ""
FnWrite-host ("[ TVORBA LABEL POLICY  ]")
FNJmenoRadku ("-") ; Write-host ""
$predtext = "Aplikuji: "

# Aplikuji 1 - 4
# Jen tohle mne stálo 5 hodin laborování$labely = $output[8] -split "," # $labely


# Vytvari se politika

#$AIPExistujiciPolicy
#$AIPExistujiciLabely
 
    $vysledek  = $AIPExistujiciPolicy.name -contains $output[0]  # True/False
    $vysledek2 = $AIPExistujiciLabely.name -contains $labely[0] # True/False

 #   $vysledek 
 #  $vysledek2

        if ($vysledek -eq $False) 
        { 
            FNJmenoRadku ("Vytvarim politiku:") ; Write-Host "Ano" -F Green

            if ($vysledek2 -eq $false) 
            { 
                FNJmenoRadku ("Aplikuji šablony:") ; FNWrite-Host "ERROR" -f RED
                $ReWritePolicyTemplate = 0 
                Write-Error = ("ERROR:`nNemozno aplikovat politiku:"+ $output[0] + "`nNenalezeny pozadovane sablony: "+ $output[4])
                BREAK 
            }
            else
            {
            FNJmenoRadku ("Aplikuji šablony:") ; FNWrite-Host $vysledek2 

                if ($WritePolicyTemplate -eq $true) 
                { 
                # TVORIM 

                $AIPExistujiciPolicy = get-labelpolicy | select Guid,Name,displayname  # Refresh informaci i policy
                }

                # MUSI JIT JAK OPRVNI 
                # 4 - ModernGroupLocation
                # Jen tohle mne stálo 5 hodin laborování                $labely = $output[8] -split ","
                FNJmenoRadku ("8  output1[8] "); FNWrite-Host ($output[8])
                if ($ReWritePolicyTemplate -eq $true -and $labely[1] -like "L????*") {
                New-LabelPolicy -Name $output[0] -Labels $labely -force | Out-Null
                }




            }
        }
        else
        {
            FNJmenoRadku ("Politika: "+$output[0]); Write-Host "Existuje" $vysledek -f RED
        }
      









# 2 - Coment to Policy
FNJmenoRadku ("2 "+$output1[2]); FNWrite-Host ($output[2]) -f White
if ($ReWritePolicyTemplate -eq $true) {
Set-LabelPolicy -identity $output[1] -Comment $output[2]
}

# 3 - ModernGroupLocation
FNJmenoRadku ("3 "+$output1[3]); FNWrite-Host ($output[3]) -f White
if ($ReWritePolicyTemplate -eq $true) {
FNJmenoRadku ("-AddModernGroupLocation"); FNWrite-Host ($output[3]) -f White
Set-LabelPolicy -identity $output[1] -AddModernGroupLocation $output[3]
}




# 7-[defaultlabelid, bd8ceefa-4ef8-4bb5-917e-9dd97d3f7a15]
FNJmenoRadku ("7 "+$output1[7]); FNWrite-Host ($output[7]) -f White
if ($ReWritePolicyTemplate -eq $true -and $output[7] -ne "none") {
[string]$prava = $output[15]

$vysledek = $AIPExistujiciLabely | where {$_.Name -eq $output[7]}
if ($vysledek -like "") { 
$vysledek.Guid
FNJmenoRadku ("7 "+$output1[7]); FNWrite-Host ($output[7]) -f White
Set-LabelPolicy -identity $output[1] -AdvancedSettings @{defaultlabelid=$vysledek.Guid}
}
}

# 10 - CustomPermissions
FNJmenoRadku ("10"+$output1[10]); FNWrite-Host ($output[10]) -f White
if ($ReWritePolicyTemplate -eq $true) {
[string]$prava = $output[10]
if ($output[10] -eq "Off") { [bool]$prava = 0 }
if ($output[10] -eq "On")  { [bool]$prava = 1 }
Set-LabelPolicy -identity $output[1] -AdvancedSettings @{requiredowngradejustification=$prava}
}


# 15 - CustomPermissions
FNJmenoRadku ("15"+$output1[15]); FNWrite-Host ($output[15]) -f White
if ($ReWritePolicyTemplate -eq $true) {
[string]$prava = $output[15]
if ($output[15] -eq "Off") { [bool]$prava = 0 }
if ($output[15] -eq "On")  { [bool]$prava = 1 }
Set-LabelPolicy -identity $output[1] -AdvancedSettings @{EnableCustomPermissions=$prava}
}


# 16 - [customurl, http://rmshelppage.local]
# Set-LabelPolicy -Identity "Global Policy" -AdvancedSettings @{EnableCustomPermissions="False"}
FNJmenoRadku ("16"+$output1[16]); FNWrite-Host ($output[16]) -f White
if ($ReWritePolicyTemplate -eq $true -and $output[16] -like "http*") {
Set-LabelPolicy -identity $output[1] -AdvancedSettings @{customurl=$output[16]}
}


}


<#################################################################################################
# Detekce kolik je v CSV setu labelu pro jednu politiku: P00001-P00002 = početradku
#################################################################################################> 

$opackocelkem = 1 # počet vzorových řádků v zdrojovém (prvním) CSV obsahuje všechny hodnoty sloupců pro nastaveni 

#############################################################################################
# 
#                                      Start Programu 
#   
#################################################################################################> 

$predtext = "$filter1 :"


#FNEndRadekPause("Načtení souborů hotovo, připravn na spuštění programu")
#cls


#############################################################################################
# 
# PRVNI CSV Soubor
#   
#################################################################################################> 
For ($r=$Startujnaradku; $r -lt $linesoncsv; $r++ ) 
{
FNHeaderProgramu
write-host "Zpracovávám $filter1 CSV, radek $r" -F Magenta

FNGetCSVLine ($r)  # Načítám data řádku.
FNNactiNazvyaHodnotySloupcu($r)
FNVypishodnot


 FNTvorbaPolitiky

# Uchovávám hodnoty posledního načteného z prvnho CSV

    if ($Output[0].length -eq 6 ){ 
    $nahrazuji = $Output[03]
    $posledni_hlavni = $r
    }

   if ($runwithpause -eq $true) { pause }



}






#############################################################################################
# 
# DRUHY CSV Soubor - OU 
#   
#################################################################################################> 
For ($hod =0 ; $hod -le $linesoncsv2; $hod++ ) {

$ou = $hod
$predtext = "$filter2 :"

FNHeaderProgramu
write-host "Zpracovávám $filter2 CSV, radek $hod" -F Magenta


do  # Tady se případně provádí smyčka (např u labelu )
{ 
 

    $labely = $nactenecsv2[$hod].Prefix 
    $emailGroupScope = $nactenecsv2[$hod].GroupScope

    FNGetCSVLine ($opacko-1)  # Načítám data řádku. (tady by se mělo načítat vždy řádek TEST 1-6)
    
    
    
}
until ($opacko -ge $opackocelkem)



 FNNactiNazvyaHodnotySloupcu($r)

$nahrazuji = "Test"
    write-host "Zpracovávám Druhý CSV, stav: $hod \ $linesoncsv2   $filter1 : $nahrazuji >> $labely - sablona: $opacko \ $opackocelkem " -F Magenta
    

            # for ($i = 1; $i -lt $pocethodnot; $i++) {
            for ($i = 1; $i -lt $pocethodnot; $i++) 
                { # Dochazi na nahrazování OU skupiny za 
                $output[$i] = $output[$i] -replace $nahrazuji,$labely
                }



    
    #  Oprava hodnoty 07 - The policy applies to : Mail  
    if ($emailGroupScope -ne "Universal" ) { $output[7] = "cez_mip_users_none@cezdata.onmicrosoft.com" }

     
    # Oprava hodnoty 01 - Policy_ID 
     $i2 = $hod + $linesoncsv
     $output[0] = "P"+$i2.ToString("00000")
     


    ## Oprava hodnoty 08 - Uprava aplikovaných šablon:
    # L00004,L00005,L00006,L00006S001,L00006S002,L00006S003
    # $output[4]="L00004,L00005,L00006,L00006S001,L00006S002,L00006S003"

    # P00001 = L00001
    # P00002 = L00004  1*3+1
    # P00003 = L00007  2*3+1
    # P00004 = L00010  3*3+1
    # P00005 = L00013  4*2+1
    # P00006 = L00016 
    # P00007 = L00019
    # P00008 = L00021

    [int]$HodOrig = $output[8].Substring(1,5)
    # $HodOrig
    $TS =  ((($r)+($hod))*3)+1
    $TS2 = $TS+1
    $TS3 = $TS+2
    $output[8] = $output[8] -replace $output[8].Substring(1,5),($TS).ToString("00000")
    $output[8] = $output[8] -replace ($HodOrig+1).ToString("00000"),$TS2.ToString("00000")
    $output[8] = $output[8] -replace ($HodOrig+2).ToString("00000"),$TS3.ToString("00000")
    # $output[8] 
           
           


           

                







                
               
                FNVypishodnot


                # FNTvorbaLabelu(0)
                # FNNastaveniLabelu(0)
                
                FNEndRadekPause("Pokračovaní")
                        
        
    }

    









"END END "

pause

